-- MySQL Script generated by MySQL Workbench
-- Wed Oct 23 16:23:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mariabonita
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mariabonita
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mariabonita` DEFAULT CHARACTER SET utf8 ;
USE `mariabonita` ;

-- -----------------------------------------------------
-- Table `mariabonita`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mariabonita`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario`),
  UNIQUE INDEX `idclientes_UNIQUE` (`idclientes` ) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mariabonita`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mariabonita`.`pedidos` (
  `idpedidos` INT NOT NULL AUTO_INCREMENT,
  `clientes_usuario` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `pagamento` VARCHAR(45) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idpedidos`),
  INDEX `fk_pedidos_clientes_idx` (`clientes_usuario` ) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mariabonita`.`pratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mariabonita`.`pratos` (
  `idpratos` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `acompanhamentos` VARCHAR(200) NOT NULL,
  `diaSemana` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(100) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `tipoCarne` VARCHAR(200) NOT NULL,
  `condicao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpratos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mariabonita`.`bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mariabonita`.`bebidas` (
  `idbebidas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(200) NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `condicao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idbebidas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mariabonita`.`itens_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mariabonita`.`itens_pedidos` (
  `iditens_pedidos` INT NULL AUTO_INCREMENT,
  `pedidos_idpedidos` INT NOT NULL,
  `quantidade_bebida` VARCHAR(45) NOT NULL,
  `quantidade_prato` VARCHAR(45) NOT NULL,
  `nome_prato` VARCHAR(255) NOT NULL,
  `nome_bebida` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`iditens_pedidos`),
  INDEX `fk_itens_pedidos_pedidos1_idx` (`pedidos_idpedidos` ) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
